### ISSUE TITLE
npm start 하니 에러가 발생하는데요. 

### ISSUE THREAD

**Issue by hygjob** [NewsJelly/jelly-chart#4]
안녕하세요.
npm start 하니 에러가 발생합니다. 

환경:
window 10 64bit 
npm 버전: 5.6.0
node 버전: 8.11.3

에러 로그는 아래와 같습니다. 

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle jelly-chart@1.3.16~prestart: jelly-chart@1.3.16
6 info lifecycle jelly-chart@1.3.16~start: jelly-chart@1.3.16
7 verbose lifecycle jelly-chart@1.3.16~start: unsafe-perm in lifecycle true

9 verbose lifecycle jelly-chart@1.3.16~start: CWD: D:\test\jelly-chart
10 silly lifecycle jelly-chart@1.3.16~start: Args: [ '/d /s /c', 'http-server -c-1 | rollup -c --watch' ]
11 silly lifecycle jelly-chart@1.3.16~start: Returned: code: 255  signal: null
12 info lifecycle jelly-chart@1.3.16~start: Failed to exec start script
13 verbose stack Error: jelly-chart@1.3.16 start: `http-server -c-1 | rollup -c --watch`
13 verbose stack Exit status 255
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid jelly-chart@1.3.16
15 verbose cwd D:\test\jelly-chart
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 255
22 error jelly-chart@1.3.16 start: `http-server -c-1 | rollup -c --watch`
22 error Exit status 255
23 error Failed at the jelly-chart@1.3.16 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 255, true ]

**Comment by luinhon** [comment]
> 22 error jelly-chart@1.3.16 start: http-server -c-1 | rollup -c --watch

위 에러는 http-server 또는 rollup 이 설치되어 있지 않은 환경이어서 발생하는 것으로 보입니다.

아래 명령어를 통해 해당 패키지 설치 후 진행해보시기 바랍니다.

`npm install http-server rollup`
